-- Copy-paste queries. Open:  .\sqlite3.exe database.db
-- Replace TABLE_ONE / TABLE_TWO / TABLE_THREE and the column names first.

.headers on
.mode column

-- ADD
-- INSERT INTO TABLE_ONE VALUES (1, '', '', '', '');

-- SEARCH
-- SELECT * FROM TABLE_ONE WHERE T1_ID = 1;

-- UPDATE
-- UPDATE TABLE_ONE SET T1_COL1 = '' WHERE T1_ID = 1;

-- DELETE
-- DELETE FROM TABLE_ONE WHERE T1_ID = 1;

-- VIEW with COUNT
SELECT COUNT(*) AS total FROM TABLE_ONE;
SELECT * FROM TABLE_ONE;

SELECT COUNT(*) AS total FROM TABLE_TWO;
SELECT * FROM TABLE_TWO;

SELECT COUNT(*) AS total FROM TABLE_THREE;
SELECT * FROM TABLE_THREE;

-- INQUIRY 1: TABLE 1 by text
SELECT COUNT(*) AS total FROM TABLE_ONE WHERE T1_SEARCH = '';
SELECT * FROM TABLE_ONE WHERE T1_SEARCH = '';

-- INQUIRY 2: TABLE 2 by age
SELECT COUNT(*) AS total FROM TABLE_TWO
WHERE (strftime('%Y','now') - strftime('%Y', T2_BDATE)) BETWEEN 0 AND 120;

-- INQUIRY 3: TABLE 3 by TABLE 2 id
SELECT COUNT(*) AS total FROM TABLE_THREE WHERE T2_ID = 1;
SELECT * FROM TABLE_THREE WHERE T2_ID = 1;

-- INQUIRY 4: TABLE 3 by TABLE 1 id
SELECT COUNT(*) AS total FROM TABLE_THREE WHERE T1_ID = 1;
SELECT * FROM TABLE_THREE WHERE T1_ID = 1;

-- INQUIRY 5: TABLE 3 by date
SELECT COUNT(*) AS total FROM TABLE_THREE
WHERE date(T3_DATE) BETWEEN '2026-01-01' AND '2026-12-31';
SELECT * FROM TABLE_THREE
WHERE date(T3_DATE) BETWEEN '2026-01-01' AND '2026-12-31';
